# Exported from Render on 2026-10-08T13:43:43Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: Game-Hub
      runtime: node
      repo: https://github.com/seethegoodofficials/Game-Hub
      plan: free
      region: oregon
      buildCommand: yarn install
      startCommand: node server.js
      autoDeployTrigger: commit
