# Exported from Render on 2026-10-08T14:39:11Z
version: "1"
projects:
- name: Game-Hub
  environments:
  - name: Production
    services:
    - type: web
      name: game-hub
      runtime: node
      repo: https://github.com/seethegoodofficials/Game-Hub
      plan: free
      region: oregon
      buildCommand: npm install
      startCommand: npm start
      autoDeployTrigger: commit
